1.1
Signed-off-by: RC1844 <1844766234@qq.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,7 +35,24 @@ jobs:
           bash _scripts/sh/create_pages.sh
           bash _scripts/sh/dump_lastmod.sh
 
-      - uses: actions-go/push@master
+      - name: Commit files
+        run: |
+          {
+              git config --local user.email "1844766234@qq.com"
+              git config --local user.name "RC1844"
+              git add .
+              git commit -m "$(date "+%Y-%m-%d %H:%M:%S")" -a
+              if [ $? -eq 0 ]; then
+                  echo "Add Update."
+              else
+                  echo "No Update."
+              fi
+          } || {
+              echo "Execution Failed"
+              exit 1
+          }
+
+      - name: Push changes
+        uses: ad-m/github-push-action@master
         with:
-          commit-message: "[Auto] update pre-puilt dist packages"
-          remote: origin
+          github_token: ${{ secrets.GITHUB_TOKEN }}
